import { app } from "electron";
import fs from "node:fs";
import path from "node:path";

/**
 * Packaged UI must load from a real directory (app.asar.unpacked), not from inside
 * app.asar — file:// ES module scripts and relative ./assets/* fail after NSIS install.
 */
function getPackagedRendererDistDir(): string {
  const unpacked = path.join(process.resourcesPath, "app.asar.unpacked", "renderer-dist");
  if (fs.existsSync(path.join(unpacked, "index.html"))) {
    return unpacked;
  }
  return path.join(app.getAppPath(), "renderer-dist");
}

/** Staged TanStack client build (generated by scripts/stage-renderer.mjs). */
export function getRendererDistDir(): string {
  if (app.isPackaged) {
    return getPackagedRendererDistDir();
  }
  return path.resolve(__dirname, "..", "..", "renderer-dist");
}

export function getProductionUiIndexPath(): string {
  return path.join(getRendererDistDir(), "index.html");
}

export function assertProductionUiAssets(): void {
  const indexPath = getProductionUiIndexPath();
  if (!fs.existsSync(indexPath)) {
    throw new Error(`Production UI index missing: ${indexPath}`);
  }
  const html = fs.readFileSync(indexPath, "utf8");
  const entry = html.match(/src="\.\/assets\/([^"]+)"/)?.[1];
  if (!entry) {
    throw new Error("Production UI index.html has no ./assets/ entry script");
  }

  const rendererDir = getRendererDistDir();
  const bundle = path.join(rendererDir, "assets", entry);
  if (!fs.existsSync(bundle)) {
    throw new Error(`Production UI entry bundle missing: ${bundle}`);
  }

  if (!html.includes('"__root__"')) {
    throw new Error("Production UI index.html is missing staged TanStack routes.__root__ manifest");
  }

  const requiredFinanceRoutes = ["/ar", "/ap", "/sales-invoicing"];
  const missingRoutes = requiredFinanceRoutes.filter((r) => !html.includes(`"${r}"`));
  if (missingRoutes.length) {
    throw new Error(
      `Production UI is outdated (missing routes: ${missingRoutes.join(", ")}). ` +
        `Run "npm run build" from the Benben_Desktop repo root, then restart the app.`,
    );
  }

  const manifestPath = path.join(rendererDir, "tsr-manifest.json");
  if (fs.existsSync(manifestPath)) {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8")) as {
      routes?: { __root__?: unknown };
      clientEntry?: string;
    };
    if (!manifest.routes?.__root__) {
      throw new Error("Production tsr-manifest.json missing routes.__root__");
    }
    const expected = `./assets/${entry}`;
    if (manifest.clientEntry && manifest.clientEntry !== expected) {
      throw new Error(
        `Production manifest clientEntry (${manifest.clientEntry}) does not match index.html (${expected})`,
      );
    }
  }
}
