/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VendorLedgerRouteImport } from './routes/vendor-ledger'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupplyChainRouteImport } from './routes/supply-chain'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesInvoicingRouteImport } from './routes/sales-invoicing'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PosRouteImport } from './routes/pos'
import { Route as MigratingRouteImport } from './routes/migrating'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HrTimecardsRouteImport } from './routes/hr-timecards'
import { Route as HrPayrollRunsRouteImport } from './routes/hr-payroll-runs'
import { Route as HrPayrollConfigRouteImport } from './routes/hr-payroll-config'
import { Route as HrEmployeesRouteImport } from './routes/hr-employees'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinanceWorkspaceRouteImport } from './routes/finance-workspace'
import { Route as FinanceTaxRouteImport } from './routes/finance-tax'
import { Route as FinanceRevRecRouteImport } from './routes/finance-rev-rec'
import { Route as FinanceReportsRouteImport } from './routes/finance-reports'
import { Route as FinancePoApprovalsRouteImport } from './routes/finance-po-approvals'
import { Route as FinanceCurrencyRouteImport } from './routes/finance-currency'
import { Route as FinanceBudgetsRouteImport } from './routes/finance-budgets'
import { Route as FinanceBankRouteImport } from './routes/finance-bank'
import { Route as FinanceAssetsRouteImport } from './routes/finance-assets'
import { Route as DataImportRouteImport } from './routes/data-import'
import { Route as CustomerLedgerRouteImport } from './routes/customer-ledger'
import { Route as Customer360RouteImport } from './routes/customer-360'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as BlindSpotVaultRouteImport } from './routes/blind-spot-vault'
import { Route as ArRouteImport } from './routes/ar'
import { Route as ApRouteImport } from './routes/ap'
import { Route as ActivityLogRouteImport } from './routes/activity-log'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLedgerRoute = VendorLedgerRouteImport.update({
  id: '/vendor-ledger',
  path: '/vendor-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyChainRoute = SupplyChainRouteImport.update({
  id: '/supply-chain',
  path: '/supply-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoicingRoute = SalesInvoicingRouteImport.update({
  id: '/sales-invoicing',
  path: '/sales-invoicing',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const MigratingRoute = MigratingRouteImport.update({
  id: '/migrating',
  path: '/migrating',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HrTimecardsRoute = HrTimecardsRouteImport.update({
  id: '/hr-timecards',
  path: '/hr-timecards',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPayrollRunsRoute = HrPayrollRunsRouteImport.update({
  id: '/hr-payroll-runs',
  path: '/hr-payroll-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPayrollConfigRoute = HrPayrollConfigRouteImport.update({
  id: '/hr-payroll-config',
  path: '/hr-payroll-config',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEmployeesRoute = HrEmployeesRouteImport.update({
  id: '/hr-employees',
  path: '/hr-employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceWorkspaceRoute = FinanceWorkspaceRouteImport.update({
  id: '/finance-workspace',
  path: '/finance-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTaxRoute = FinanceTaxRouteImport.update({
  id: '/finance-tax',
  path: '/finance-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRevRecRoute = FinanceRevRecRouteImport.update({
  id: '/finance-rev-rec',
  path: '/finance-rev-rec',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/finance-reports',
  path: '/finance-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePoApprovalsRoute = FinancePoApprovalsRouteImport.update({
  id: '/finance-po-approvals',
  path: '/finance-po-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCurrencyRoute = FinanceCurrencyRouteImport.update({
  id: '/finance-currency',
  path: '/finance-currency',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBudgetsRoute = FinanceBudgetsRouteImport.update({
  id: '/finance-budgets',
  path: '/finance-budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBankRoute = FinanceBankRouteImport.update({
  id: '/finance-bank',
  path: '/finance-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAssetsRoute = FinanceAssetsRouteImport.update({
  id: '/finance-assets',
  path: '/finance-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const DataImportRoute = DataImportRouteImport.update({
  id: '/data-import',
  path: '/data-import',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLedgerRoute = CustomerLedgerRouteImport.update({
  id: '/customer-ledger',
  path: '/customer-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const Customer360Route = Customer360RouteImport.update({
  id: '/customer-360',
  path: '/customer-360',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BlindSpotVaultRoute = BlindSpotVaultRouteImport.update({
  id: '/blind-spot-vault',
  path: '/blind-spot-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApRoute = ApRouteImport.update({
  id: '/ap',
  path: '/ap',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogRoute = ActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/activate': typeof ActivateRoute
  '/activity-log': typeof ActivityLogRoute
  '/ap': typeof ApRoute
  '/ar': typeof ArRoute
  '/blind-spot-vault': typeof BlindSpotVaultRoute
  '/change-password': typeof ChangePasswordRoute
  '/crm': typeof CrmRoute
  '/customer-360': typeof Customer360Route
  '/customer-ledger': typeof CustomerLedgerRoute
  '/data-import': typeof DataImportRoute
  '/finance-assets': typeof FinanceAssetsRoute
  '/finance-bank': typeof FinanceBankRoute
  '/finance-budgets': typeof FinanceBudgetsRoute
  '/finance-currency': typeof FinanceCurrencyRoute
  '/finance-po-approvals': typeof FinancePoApprovalsRoute
  '/finance-reports': typeof FinanceReportsRoute
  '/finance-rev-rec': typeof FinanceRevRecRoute
  '/finance-tax': typeof FinanceTaxRoute
  '/finance-workspace': typeof FinanceWorkspaceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/hr-employees': typeof HrEmployeesRoute
  '/hr-payroll-config': typeof HrPayrollConfigRoute
  '/hr-payroll-runs': typeof HrPayrollRunsRoute
  '/hr-timecards': typeof HrTimecardsRoute
  '/import': typeof ImportRoute
  '/imports': typeof ImportsRoute
  '/inventory': typeof InventoryRoute
  '/landing': typeof LandingRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/manufacturing': typeof ManufacturingRoute
  '/migrating': typeof MigratingRoute
  '/pos': typeof PosRoute
  '/privacy': typeof PrivacyRoute
  '/purchasing': typeof PurchasingRoute
  '/refunds': typeof RefundsRoute
  '/sales-invoicing': typeof SalesInvoicingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/supply-chain': typeof SupplyChainRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/vendor-ledger': typeof VendorLedgerRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/activate': typeof ActivateRoute
  '/activity-log': typeof ActivityLogRoute
  '/ap': typeof ApRoute
  '/ar': typeof ArRoute
  '/blind-spot-vault': typeof BlindSpotVaultRoute
  '/change-password': typeof ChangePasswordRoute
  '/crm': typeof CrmRoute
  '/customer-360': typeof Customer360Route
  '/customer-ledger': typeof CustomerLedgerRoute
  '/data-import': typeof DataImportRoute
  '/finance-assets': typeof FinanceAssetsRoute
  '/finance-bank': typeof FinanceBankRoute
  '/finance-budgets': typeof FinanceBudgetsRoute
  '/finance-currency': typeof FinanceCurrencyRoute
  '/finance-po-approvals': typeof FinancePoApprovalsRoute
  '/finance-reports': typeof FinanceReportsRoute
  '/finance-rev-rec': typeof FinanceRevRecRoute
  '/finance-tax': typeof FinanceTaxRoute
  '/finance-workspace': typeof FinanceWorkspaceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/hr-employees': typeof HrEmployeesRoute
  '/hr-payroll-config': typeof HrPayrollConfigRoute
  '/hr-payroll-runs': typeof HrPayrollRunsRoute
  '/hr-timecards': typeof HrTimecardsRoute
  '/import': typeof ImportRoute
  '/imports': typeof ImportsRoute
  '/inventory': typeof InventoryRoute
  '/landing': typeof LandingRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/manufacturing': typeof ManufacturingRoute
  '/migrating': typeof MigratingRoute
  '/pos': typeof PosRoute
  '/privacy': typeof PrivacyRoute
  '/purchasing': typeof PurchasingRoute
  '/refunds': typeof RefundsRoute
  '/sales-invoicing': typeof SalesInvoicingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/supply-chain': typeof SupplyChainRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/vendor-ledger': typeof VendorLedgerRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/activate': typeof ActivateRoute
  '/activity-log': typeof ActivityLogRoute
  '/ap': typeof ApRoute
  '/ar': typeof ArRoute
  '/blind-spot-vault': typeof BlindSpotVaultRoute
  '/change-password': typeof ChangePasswordRoute
  '/crm': typeof CrmRoute
  '/customer-360': typeof Customer360Route
  '/customer-ledger': typeof CustomerLedgerRoute
  '/data-import': typeof DataImportRoute
  '/finance-assets': typeof FinanceAssetsRoute
  '/finance-bank': typeof FinanceBankRoute
  '/finance-budgets': typeof FinanceBudgetsRoute
  '/finance-currency': typeof FinanceCurrencyRoute
  '/finance-po-approvals': typeof FinancePoApprovalsRoute
  '/finance-reports': typeof FinanceReportsRoute
  '/finance-rev-rec': typeof FinanceRevRecRoute
  '/finance-tax': typeof FinanceTaxRoute
  '/finance-workspace': typeof FinanceWorkspaceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/hr-employees': typeof HrEmployeesRoute
  '/hr-payroll-config': typeof HrPayrollConfigRoute
  '/hr-payroll-runs': typeof HrPayrollRunsRoute
  '/hr-timecards': typeof HrTimecardsRoute
  '/import': typeof ImportRoute
  '/imports': typeof ImportsRoute
  '/inventory': typeof InventoryRoute
  '/landing': typeof LandingRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/manufacturing': typeof ManufacturingRoute
  '/migrating': typeof MigratingRoute
  '/pos': typeof PosRoute
  '/privacy': typeof PrivacyRoute
  '/purchasing': typeof PurchasingRoute
  '/refunds': typeof RefundsRoute
  '/sales-invoicing': typeof SalesInvoicingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/supply-chain': typeof SupplyChainRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/vendor-ledger': typeof VendorLedgerRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/activate'
    | '/activity-log'
    | '/ap'
    | '/ar'
    | '/blind-spot-vault'
    | '/change-password'
    | '/crm'
    | '/customer-360'
    | '/customer-ledger'
    | '/data-import'
    | '/finance-assets'
    | '/finance-bank'
    | '/finance-budgets'
    | '/finance-currency'
    | '/finance-po-approvals'
    | '/finance-reports'
    | '/finance-rev-rec'
    | '/finance-tax'
    | '/finance-workspace'
    | '/forgot-password'
    | '/help'
    | '/hr-employees'
    | '/hr-payroll-config'
    | '/hr-payroll-runs'
    | '/hr-timecards'
    | '/import'
    | '/imports'
    | '/inventory'
    | '/landing'
    | '/locations'
    | '/login'
    | '/manufacturing'
    | '/migrating'
    | '/pos'
    | '/privacy'
    | '/purchasing'
    | '/refunds'
    | '/sales-invoicing'
    | '/settings'
    | '/setup'
    | '/supply-chain'
    | '/terms'
    | '/users'
    | '/vendor-ledger'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/activate'
    | '/activity-log'
    | '/ap'
    | '/ar'
    | '/blind-spot-vault'
    | '/change-password'
    | '/crm'
    | '/customer-360'
    | '/customer-ledger'
    | '/data-import'
    | '/finance-assets'
    | '/finance-bank'
    | '/finance-budgets'
    | '/finance-currency'
    | '/finance-po-approvals'
    | '/finance-reports'
    | '/finance-rev-rec'
    | '/finance-tax'
    | '/finance-workspace'
    | '/forgot-password'
    | '/help'
    | '/hr-employees'
    | '/hr-payroll-config'
    | '/hr-payroll-runs'
    | '/hr-timecards'
    | '/import'
    | '/imports'
    | '/inventory'
    | '/landing'
    | '/locations'
    | '/login'
    | '/manufacturing'
    | '/migrating'
    | '/pos'
    | '/privacy'
    | '/purchasing'
    | '/refunds'
    | '/sales-invoicing'
    | '/settings'
    | '/setup'
    | '/supply-chain'
    | '/terms'
    | '/users'
    | '/vendor-ledger'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/activate'
    | '/activity-log'
    | '/ap'
    | '/ar'
    | '/blind-spot-vault'
    | '/change-password'
    | '/crm'
    | '/customer-360'
    | '/customer-ledger'
    | '/data-import'
    | '/finance-assets'
    | '/finance-bank'
    | '/finance-budgets'
    | '/finance-currency'
    | '/finance-po-approvals'
    | '/finance-reports'
    | '/finance-rev-rec'
    | '/finance-tax'
    | '/finance-workspace'
    | '/forgot-password'
    | '/help'
    | '/hr-employees'
    | '/hr-payroll-config'
    | '/hr-payroll-runs'
    | '/hr-timecards'
    | '/import'
    | '/imports'
    | '/inventory'
    | '/landing'
    | '/locations'
    | '/login'
    | '/manufacturing'
    | '/migrating'
    | '/pos'
    | '/privacy'
    | '/purchasing'
    | '/refunds'
    | '/sales-invoicing'
    | '/settings'
    | '/setup'
    | '/supply-chain'
    | '/terms'
    | '/users'
    | '/vendor-ledger'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  ActivateRoute: typeof ActivateRoute
  ActivityLogRoute: typeof ActivityLogRoute
  ApRoute: typeof ApRoute
  ArRoute: typeof ArRoute
  BlindSpotVaultRoute: typeof BlindSpotVaultRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CrmRoute: typeof CrmRoute
  Customer360Route: typeof Customer360Route
  CustomerLedgerRoute: typeof CustomerLedgerRoute
  DataImportRoute: typeof DataImportRoute
  FinanceAssetsRoute: typeof FinanceAssetsRoute
  FinanceBankRoute: typeof FinanceBankRoute
  FinanceBudgetsRoute: typeof FinanceBudgetsRoute
  FinanceCurrencyRoute: typeof FinanceCurrencyRoute
  FinancePoApprovalsRoute: typeof FinancePoApprovalsRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FinanceRevRecRoute: typeof FinanceRevRecRoute
  FinanceTaxRoute: typeof FinanceTaxRoute
  FinanceWorkspaceRoute: typeof FinanceWorkspaceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HrEmployeesRoute: typeof HrEmployeesRoute
  HrPayrollConfigRoute: typeof HrPayrollConfigRoute
  HrPayrollRunsRoute: typeof HrPayrollRunsRoute
  HrTimecardsRoute: typeof HrTimecardsRoute
  ImportRoute: typeof ImportRoute
  ImportsRoute: typeof ImportsRoute
  InventoryRoute: typeof InventoryRoute
  LandingRoute: typeof LandingRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  ManufacturingRoute: typeof ManufacturingRoute
  MigratingRoute: typeof MigratingRoute
  PosRoute: typeof PosRoute
  PrivacyRoute: typeof PrivacyRoute
  PurchasingRoute: typeof PurchasingRoute
  RefundsRoute: typeof RefundsRoute
  SalesInvoicingRoute: typeof SalesInvoicingRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SupplyChainRoute: typeof SupplyChainRoute
  TermsRoute: typeof TermsRoute
  UsersRoute: typeof UsersRoute
  VendorLedgerRoute: typeof VendorLedgerRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-ledger': {
      id: '/vendor-ledger'
      path: '/vendor-ledger'
      fullPath: '/vendor-ledger'
      preLoaderRoute: typeof VendorLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-chain': {
      id: '/supply-chain'
      path: '/supply-chain'
      fullPath: '/supply-chain'
      preLoaderRoute: typeof SupplyChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-invoicing': {
      id: '/sales-invoicing'
      path: '/sales-invoicing'
      fullPath: '/sales-invoicing'
      preLoaderRoute: typeof SalesInvoicingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrating': {
      id: '/migrating'
      path: '/migrating'
      fullPath: '/migrating'
      preLoaderRoute: typeof MigratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-timecards': {
      id: '/hr-timecards'
      path: '/hr-timecards'
      fullPath: '/hr-timecards'
      preLoaderRoute: typeof HrTimecardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-payroll-runs': {
      id: '/hr-payroll-runs'
      path: '/hr-payroll-runs'
      fullPath: '/hr-payroll-runs'
      preLoaderRoute: typeof HrPayrollRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-payroll-config': {
      id: '/hr-payroll-config'
      path: '/hr-payroll-config'
      fullPath: '/hr-payroll-config'
      preLoaderRoute: typeof HrPayrollConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-employees': {
      id: '/hr-employees'
      path: '/hr-employees'
      fullPath: '/hr-employees'
      preLoaderRoute: typeof HrEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-workspace': {
      id: '/finance-workspace'
      path: '/finance-workspace'
      fullPath: '/finance-workspace'
      preLoaderRoute: typeof FinanceWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-tax': {
      id: '/finance-tax'
      path: '/finance-tax'
      fullPath: '/finance-tax'
      preLoaderRoute: typeof FinanceTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-rev-rec': {
      id: '/finance-rev-rec'
      path: '/finance-rev-rec'
      fullPath: '/finance-rev-rec'
      preLoaderRoute: typeof FinanceRevRecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-reports': {
      id: '/finance-reports'
      path: '/finance-reports'
      fullPath: '/finance-reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-po-approvals': {
      id: '/finance-po-approvals'
      path: '/finance-po-approvals'
      fullPath: '/finance-po-approvals'
      preLoaderRoute: typeof FinancePoApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-currency': {
      id: '/finance-currency'
      path: '/finance-currency'
      fullPath: '/finance-currency'
      preLoaderRoute: typeof FinanceCurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-budgets': {
      id: '/finance-budgets'
      path: '/finance-budgets'
      fullPath: '/finance-budgets'
      preLoaderRoute: typeof FinanceBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-bank': {
      id: '/finance-bank'
      path: '/finance-bank'
      fullPath: '/finance-bank'
      preLoaderRoute: typeof FinanceBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-assets': {
      id: '/finance-assets'
      path: '/finance-assets'
      fullPath: '/finance-assets'
      preLoaderRoute: typeof FinanceAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-import': {
      id: '/data-import'
      path: '/data-import'
      fullPath: '/data-import'
      preLoaderRoute: typeof DataImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-ledger': {
      id: '/customer-ledger'
      path: '/customer-ledger'
      fullPath: '/customer-ledger'
      preLoaderRoute: typeof CustomerLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-360': {
      id: '/customer-360'
      path: '/customer-360'
      fullPath: '/customer-360'
      preLoaderRoute: typeof Customer360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blind-spot-vault': {
      id: '/blind-spot-vault'
      path: '/blind-spot-vault'
      fullPath: '/blind-spot-vault'
      preLoaderRoute: typeof BlindSpotVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ap': {
      id: '/ap'
      path: '/ap'
      fullPath: '/ap'
      preLoaderRoute: typeof ApRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-log': {
      id: '/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof ActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  ActivateRoute: ActivateRoute,
  ActivityLogRoute: ActivityLogRoute,
  ApRoute: ApRoute,
  ArRoute: ArRoute,
  BlindSpotVaultRoute: BlindSpotVaultRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CrmRoute: CrmRoute,
  Customer360Route: Customer360Route,
  CustomerLedgerRoute: CustomerLedgerRoute,
  DataImportRoute: DataImportRoute,
  FinanceAssetsRoute: FinanceAssetsRoute,
  FinanceBankRoute: FinanceBankRoute,
  FinanceBudgetsRoute: FinanceBudgetsRoute,
  FinanceCurrencyRoute: FinanceCurrencyRoute,
  FinancePoApprovalsRoute: FinancePoApprovalsRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FinanceRevRecRoute: FinanceRevRecRoute,
  FinanceTaxRoute: FinanceTaxRoute,
  FinanceWorkspaceRoute: FinanceWorkspaceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HrEmployeesRoute: HrEmployeesRoute,
  HrPayrollConfigRoute: HrPayrollConfigRoute,
  HrPayrollRunsRoute: HrPayrollRunsRoute,
  HrTimecardsRoute: HrTimecardsRoute,
  ImportRoute: ImportRoute,
  ImportsRoute: ImportsRoute,
  InventoryRoute: InventoryRoute,
  LandingRoute: LandingRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  ManufacturingRoute: ManufacturingRoute,
  MigratingRoute: MigratingRoute,
  PosRoute: PosRoute,
  PrivacyRoute: PrivacyRoute,
  PurchasingRoute: PurchasingRoute,
  RefundsRoute: RefundsRoute,
  SalesInvoicingRoute: SalesInvoicingRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SupplyChainRoute: SupplyChainRoute,
  TermsRoute: TermsRoute,
  UsersRoute: UsersRoute,
  VendorLedgerRoute: VendorLedgerRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
